name: Generate Snake Images

on:
  schedule:
    - cron: "0 0 * * *"     # corre cada día a medianoche UTC
  workflow_dispatch:        # permite ejecutarlo manualmente

permissions:
  contents: write           # necesario para actualizar la rama 'output'

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate contribution snake images
        uses: Platane/snk@v3
        with:
          github_user_name: DevKonnyAlucema

      - name: Publish generated images to 'output' branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
